// Localidades destacadas (aparecen primero)
export const LOCALIDADES_DESTACADAS = ['Balcarce', 'Mar del Plata']

// Partidos/localidades de la Provincia de Buenos Aires
export const LOCALIDADES_BUENOS_AIRES = [
  'Adolfo Alsina',
  'Adolfo Gonzales Chaves',
  'Alberti',
  'Almirante Brown',
  'Arrecifes',
  'Avellaneda',
  'Ayacucho',
  'Azul',
  'Bahia Blanca',
  'Balcarce',
  'Baradero',
  'Batán',
  'Benavídez',
  'Benito Juárez',
  'Berazategui',
  'Berisso',
  'Bolívar',
  'Boulogne',
  'Bragado',
  'Brandsen',
  'Campana',
  'Cañuelas',
  'Capitán Sarmiento',
  'Carlos Casares',
  'Carlos Tejedor',
  'Carmen de Areco',
  'Carmen de Patagones',
  'Castelli',
  'Chacabuco',
  'Chascomús',
  'Chivilcoy',
  'Claypole',
  'Colón',
  'Coronel Dorrego',
  'Coronel Pringles',
  'Coronel Rosales',
  'Coronel Suárez',
  'Daireaux',
  'Del Viso',
  'Dolores',
  'Don Torcuato',
  'Ensenada',
  'Escobar',
  'Esteban Echeverría',
  'Exaltación de la Cruz',
  'Ezeiza',
  'Florencio Varela',
  'Florentino Ameghino',
  'General Alvarado',
  'General Alvear',
  'General Arenales',
  'General Belgrano',
  'General Guido',
  'General Juan Madariaga',
  'General La Madrid',
  'General Las Heras',
  'General Lavalle',
  'General Pacheco',
  'General Paz',
  'General Pinto',
  'General Pueyrredón',
  'General Rodríguez',
  'General San Martín',
  'General Viamonte',
  'General Villegas',
  'Gonnet',
  'González Catán',
  'Grand Bourg',
  'Guaminí',
  'Haedo',
  'Henderson',
  'Hipólito Yrigoyen',
  'Hurlingham',
  'Ingeniero Maschwitz',
  'Ituzaingó',
  'José C. Paz',
  'Junín',
  'La Matanza',
  'La Plata',
  'Lanús',
  'Laprida',
  'Las Flores',
  'Las Toninas',
  'Leandro N. Alem',
  'Lincoln',
  'Lobería',
  'Lobos',
  'Lomas de Zamora',
  'Los Polvorines',
  'Luján',
  'Magdalena',
  'Maipú',
  'Malvinas Argentinas',
  'Mar de Ajó',
  'Mar de las Pampas',
  'Mar del Plata',
  'Mar del Tuyú',
  'Marcos Paz',
  'Mercedes',
  'Merlo',
  'Miramar',
  'Monte',
  'Monte Grande',
  'Monte Hermoso',
  'Moreno',
  'Morón',
  'Munro',
  'Navarro',
  'Necochea',
  'Nueve de Julio',
  'Olavarría',
  'Olivos',
  'Pablo Nogués',
  'Partido de la Costa',
  'Pehuajó',
  'Pellegrini',
  'Pergamino',
  'Pigüé',
  'Pilar',
  'Pinamar',
  'Presidente Perón',
  'Puan',
  'Punta Alta',
  'Punta Indio',
  'Quilmes',
  'Ramallo',
  'Ramos Mejía',
  'Rauch',
  'Rivadavia',
  'Rojas',
  'Roque Pérez',
  'Saladillo',
  'Salliqueló',
  'Salto',
  'San Andrés de Giles',
  'San Antonio de Areco',
  'San Antonio de Padua',
  'San Bernardo',
  'San Cayetano',
  'San Clemente del Tuyú',
  'San Fernando',
  'San Isidro',
  'San Justo',
  'San Miguel',
  'San Miguel del Monte',
  'San Nicolás',
  'San Pedro',
  'San Vicente',
  'Santa Teresita',
  'Santos Lugares',
  'Sarandí',
  'Sierra de la Ventana',
  'Sierra de los Padres',
  'Suipacha',
  'Tandil',
  'Tapalqué',
  'Temperley',
  'Tigre',
  'Tornquist',
  'Trenque Lauquen',
  'Tres Arroyos',
  'Tres de Febrero',
  'Tres Lomas',
  'Vicente López',
  'Victoria',
  'Villa Ballester',
  'Villa Elisa',
  'Villa Gesell',
  'Villa Luzuriaga',
  'Villa María',
  'Villarino',
  'Zárate',
]

export function getLocalidadesOrdenadas(): string[] {
  const rest = LOCALIDADES_BUENOS_AIRES
    .filter(l => !LOCALIDADES_DESTACADAS.includes(l))
    .sort((a, b) => a.localeCompare(b, 'es'))
  return [...LOCALIDADES_DESTACADAS, '---', ...rest]
}
